name: Sync Changes to All Repositories

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          repository: engineercode36/broken-barrier-progress

      - name: Set Up Git
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"

      - name: Sync with Other Repositories
        run: |
          # List of repositories to sync
          REPOS=(
            "https://github.com/canlife4ever/note-haven-syntax-21.git"
          )

          # Configure authentication using hardcoded token
          TOKEN="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"
          git config --global credential.helper store
          echo "https://${TOKEN}:@github.com" > ~/.git-credentials

          # Loop through each repository and push changes
          for repo in "${REPOS[@]}"; do
            echo "Syncing with $repo"
            git remote add target "$repo"
            if git push --mirror target; then
              echo "Successfully pushed to $repo"
            else
              echo "Failed to push to $repo"
            fi
            git remote remove target
          done
