name: Sync Repositories

on:
  workflow_dispatch:  # Trigger manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for target repo access

    - name: Clone Source Repository
      run: |
        # Hardcode the source repo's URL with your PAT (this is just for testing)
        git remote add source https://engineercode36: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@github.com/engineercode36/broken-barrier-progress.git
        
        # Fetch the source repo
        git fetch source
        
        # Merge from source repo to target
        git merge source/main --allow-unrelated-histories
        
        # Push the changes to the target repository
        git push origin main
