name: Upload Files to Repository

on:
  push:
    branches:
      - main  # Run this on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  upload-files:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: engineercode36/broken-barrier-progress  # Specify your repository

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config --global user.name "engineercode36"
          git config --global user.email "engineercode36@proton.me"

      # Step 3: Copy your files into the repository
      - name: Upload files
        run: |
          mkdir -p upload_folder
          cp -r '/mnt/c/Users/Nati/Desktop/Rigorous 2025/0/*' upload_folder/

      # Step 4: Commit and push the changes
      - name: Commit and push files
        run: |
          git add upload_folder/
          git commit -m "Upload new files"
          git push https://github.com/engineercode36/broken-barrier-progress.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
